apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hello-api
spec:
  ingressClassName: nginx
  rules:
    - host: hello.localtest.me # replaced per environment by the overlays
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: hello-api
                port:
                  name: http
